# Eat Safe, Love

## Notebook Set Up

In [134]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint
import pandas as pd 
import matplotlib as plt

In [135]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [136]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [137]:
# review the collections in our database
db.list_collection_names()

['establishments']

In [138]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [139]:
# Find the establishments with a hygiene score of 20
query = {'scores.Hygiene': {'$eq': 20}}

# Use count_documents to display the number of documents in the result
scores_of_20 = db.establishments.count_documents(query)
print(f"There are {scores_of_20} establishments with a hygiene score of 20")

# Display the first document in the results using pprint
results = db.establishments.find(query)

pprint(results[0])

There are 41 establishments with a hygiene score of 20
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': '0',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('63cc960526f9d622e55d1734'),
 'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [140]:
# Convert the result to a Pandas DataFrame
result_df = pd.DataFrame(results)

# Display the number of rows in the DataFrame
print(f"Number of rows in dataset: ", len(result_df))

# Display the first 10 rows of the DataFrame
result_df.head(10)

Number of rows in dataset:  41

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links,longitude,latitude
0,63cc960526f9d622e55d1734,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.27694, 'latitude': 50.769705}",,4613.888288,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
1,63cc960526f9d622e55d1ab6,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 1.278721, 'latitude': 51.857536}",,4617.965824,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
2,63cc960626f9d622e55d1dc8,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 1.15927, 'latitude': 51.789429}",,4619.656144,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
3,63cc960626f9d622e55d1fb5,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.10202, 'latitude': 50.770885}",,4620.421725,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
4,63cc960626f9d622e55d1fbe,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.101446, 'latitude': 50.770724}",,4620.437179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
5,63cc960626f9d622e55d2959,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.736349, 'latitude': 51.541448}",,4625.565258,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
6,63cc960626f9d622e55d2b8c,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.7121671, 'latitude': 51.5350065}",,4626.200132,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
7,63cc960726f9d622e55d40a6,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 0.602364, 'latitude': 51.591515}",,4632.276890,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
8,63cc960726f9d622e55d44ec,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,"{'Hygiene': 20, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 0.146449998021126, 'latitude': 5...",,4633.934041,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
9,63cc960726f9d622e55d4cfc,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.462307, 'latitude': 51.57005}",,4636.552523,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [141]:
db.establishments.find_one()

{'_id': ObjectId('63cc960426f9d622e55cfc03'),
 'FHRSID': 1043695,
 'ChangesByServerID': 0,
 'LocalAuthorityBusinessID': 'PI/000073616',
 'BusinessName': 'The Pavilion',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 1,
 'AddressLine1': 'East Cliff Pavilion',
 'AddressLine2': 'Wear Bay Road',
 'AddressLine3': 'Folkestone',
 'AddressLine4': 'Kent',
 'PostCode': 'CT19 6BL',
 'Phone': '',
 'RatingValue': 5.0,
 'RatingKey': 'fhrs_5_en-gb',
 'RatingDate': '2018-04-04T00:00:00',
 'LocalAuthorityCode': '188',
 'LocalAuthorityName': 'Folkestone and Hythe',
 'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
 'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
 'scores': {'Hygiene': 5, 'Structural': 5, 'ConfidenceInManagement': 5},
 'SchemeType': 'FHRS',
 'geocode': {'longitude': 1.195625, 'latitude': 51.083812},
 'RightToReply': '',
 'Distance': 4591.765489457773,
 'NewRatingPending': False,
 'meta': {'dataSource': None,
  'extractDate': '0001-01-01T00:00:00',
  'itemCount': 0,
  'returncode': None,
  'totalCount': 0,
  'totalPages': 0,
  'pageSize': 0,
  'pageNumber': 0},
 'links': [{'rel': 'self',
   'href': 'https://api.ratings.food.gov.uk/establishments/1043695'}],
 'longitude': None,
 'latitude': None}

In [142]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {
            'LocalAuthorityName': {'$regex': 'London'},
            'RatingValue': {'$gte': '4'}
        }
        

# Use count_documents to display the number of documents in the result
establishments.count_documents(query)

# Display the first document in the results using pprint
results = establishments.find(query)

pprint(results[0])

{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': '4',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('63cc960626f9d622e55d314e'),
 'geocode': {'latitude': 51.369321, 'longitude': 0.508551},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [143]:
# Convert the result to a Pandas DataFrame
results_df = pd.DataFrame(results)

# Display the number of rows in the DataFrame
print("Number of rows in dataset is: ", len(results_df))
# Display the first 10 rows of the DataFrame

Number of rows in dataset is:  34

### 3. What are the top 5 establishments with a `RatingValue` rating value of '5', sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [149]:
# Check that the new restaurant was inserted
results = establishments.find({'BusinessName': 'Penang Flavours'})

pprint(list(results))

[{'AddressLine1': 'Penang Flavours',
  'AddressLine2': '146A Plumstead Rd',
  'AddressLine3': 'London',
  'AddressLine4': '',
  'BusinessName': 'Penang Flavours',
  'BusinessType': 'Restaurant/Cafe/Canteen',
  'BusinessTypeID': 1,
  'Distance': 4623.972328074718,
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': True,
  'Phone': '',
  'PostCode': 'SE18 7DY',
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('63cc980afe78af6bc163fb28'),
  'geocode': {'latitude': 51.490142, 'longitude': 0.08384},
  'latitude': None,
  'longitude': None,
  'scores': {'ConfidenceInManagement': '', 'Hygiene': '', 'Structural': ''}},
 {'AddressLine1': 'Penang Flavours',
  'AddressLine2': '146A Plumstead Rd',
  'AddressLine3': 'London',
  'AddressLine4': '',
  'BusinessName': 'Penang Flavours',
  'BusinessType': 'Restaurant/Cafe/Canteen',
  'BusinessTypeID': 1,
  'Distance': 4623.972328074718,
  'LocalAuthorityCode': '511',
  'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
  'LocalAuthorityName': 'Greenwich',
  'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
  'NewRatingPending': True,
  'Phone': '',
  'PostCode': 'SE18 7DY',
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('63ccabaafe78af6bc163fb2a'),
  'geocode': {'latitude': 51.490142, 'longitude': 0.08384},
  'scores': {'ConfidenceInManagement': '', 'Hygiene': '', 'Structural': ''}}]

In [248]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
latitude = 51.490142
longitude = 0.08384

query = {'geocode.latitude': {'$gte': latitude - degree_search, '$lte': latitude + degree_search},
         'geocode.longitude': {'$gte': longitude - degree_search, '$lte': longitude + degree_search},
         'RatingValue': {'$eq': '5'}}

fields = {'geocode.latitude': 1,
          'geocode.longitude': 1,
          'RatingValue': 1, 
          'scores.Hygiene': 1
          }

sort =  [('scores.Hygiene', 1)]


results = list(establishments.find(query, fields).sort(sort))

# Print the results
pprint(results)

[{'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d6f68'),
  'geocode': {'latitude': 51.4871482849121, 'longitude': 0.0924199968576431},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d6f76'),
  'geocode': {'latitude': 51.4875335693359, 'longitude': 0.0925370007753372},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d6f93'),
  'geocode': {'latitude': 51.4873437, 'longitude': 0.09208},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d6fab'),
  'geocode': {'latitude': 51.481517791748, 'longitude': 0.0859939977526665},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d6faf'),
  'geocode': {'latitude': 51.4867296, 'longitude': 0.0912164},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d6fb1'),
  'geocode': {'latitude': 51.4871632, 'longitude': 0.0916256},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d6fcf'),
  'geocode': {'latitude': 51.4871406555176, 'longitude': 0.0912820026278496},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d6fd2'),
  'geocode': {'latitude': 51.4871406555176, 'longitude': 0.0912820026278496},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d6ff4'),
  'geocode': {'latitude': 51.4877576, 'longitude': 0.091566},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d6ff9'),
  'geocode': {'latitude': 51.4871401, 'longitude': 0.0908895},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7036'),
  'geocode': {'latitude': 51.4878941, 'longitude': 0.0909672},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7049'),
  'geocode': {'latitude': 51.4876894, 'longitude': 0.0905233},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7054'),
  'geocode': {'latitude': 51.4876718, 'longitude': 0.0903232},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7068'),
  'geocode': {'latitude': 51.4817109, 'longitude': 0.0840959},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d707b'),
  'geocode': {'latitude': 51.487928, 'longitude': 0.0900757},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7092'),
  'geocode': {'latitude': 51.4880687, 'longitude': 0.0897508},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7098'),
  'geocode': {'latitude': 51.487865447998, 'longitude': 0.0894860029220581},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d70aa'),
  'geocode': {'latitude': 51.4881611, 'longitude': 0.089611},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d70c4'),
  'geocode': {'latitude': 51.4881627, 'longitude': 0.0895246},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d70d9'),
  'geocode': {'latitude': 51.4884195010951, 'longitude': 0.0893575026992294},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d70ec'),
  'geocode': {'latitude': 51.4827461242676, 'longitude': 0.0831020027399063},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d70f8'),
  'geocode': {'latitude': 51.4884997, 'longitude': 0.0887766},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d70fb'),
  'geocode': {'latitude': 51.4806876203642, 'longitude': 0.0808583091748281},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d710a'),
  'geocode': {'latitude': 51.4885934, 'longitude': 0.0885648},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7146'),
  'geocode': {'latitude': 51.4810979, 'longitude': 0.0802144},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7148'),
  'geocode': {'latitude': 51.4845542907715, 'longitude': 0.0836590006947517},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d715c'),
  'geocode': {'latitude': 51.4806732, 'longitude': 0.0793165},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7169'),
  'geocode': {'latitude': 51.4860247, 'longitude': 0.0843422},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7171'),
  'geocode': {'latitude': 51.4890121, 'longitude': 0.0868772},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7173'),
  'geocode': {'latitude': 51.487438, 'longitude': 0.0852709},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d717d'),
  'geocode': {'latitude': 51.4808120727539, 'longitude': 0.0785060003399849},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7188'),
  'geocode': {'latitude': 51.4838756, 'longitude': 0.0812914},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7189'),
  'geocode': {'latitude': 51.4847465, 'longitude': 0.0820677},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7196'),
  'geocode': {'latitude': 51.4892023, 'longitude': 0.086187},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d719a'),
  'geocode': {'latitude': 51.4884185791016, 'longitude': 0.0853480026125908},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d719b'),
  'geocode': {'latitude': 51.4892216, 'longitude': 0.0861158},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d71a3'),
  'geocode': {'latitude': 51.484673, 'longitude': 0.0814574},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d71c7'),
  'geocode': {'latitude': 51.4896464707035, 'longitude': 0.0857344851907352},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d71c8'),
  'geocode': {'latitude': 51.4893348, 'longitude': 0.0853618},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7201'),
  'geocode': {'latitude': 51.4908567, 'longitude': 0.0853967},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d720a'),
  'geocode': {'latitude': 51.4900815, 'longitude': 0.0842824},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d720d'),
  'geocode': {'latitude': 51.4897501, 'longitude': 0.0839053},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7215'),
  'geocode': {'latitude': 51.4862246, 'longitude': 0.0801741},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7218'),
  'geocode': {'latitude': 51.4901495, 'longitude': 0.0839974},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d721e'),
  'geocode': {'latitude': 51.4873504638672, 'longitude': 0.0810069963335991},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7221'),
  'geocode': {'latitude': 51.4835927, 'longitude': 0.0771598},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7237'),
  'geocode': {'latitude': 51.486075, 'longitude': 0.0789717},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7241'),
  'geocode': {'latitude': 51.4903258, 'longitude': 0.0824813},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7246'),
  'geocode': {'latitude': 51.4824142456055, 'longitude': 0.074412003159523},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7247'),
  'geocode': {'latitude': 51.4824256896973, 'longitude': 0.0743729993700981},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7258'),
  'geocode': {'latitude': 51.4863967895508, 'longitude': 0.0776320025324821},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7259'),
  'geocode': {'latitude': 51.4863955, 'longitude': 0.0776292},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d725d'),
  'geocode': {'latitude': 51.4989512, 'longitude': 0.0902181},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7267'),
  'geocode': {'latitude': 51.4987492, 'longitude': 0.0895991},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d72b7'),
  'geocode': {'latitude': 51.4871520996094, 'longitude': 0.075984999537468},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d72ba'),
  'geocode': {'latitude': 51.4940567016602, 'longitude': 0.0827509984374046},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d72c9'),
  'geocode': {'latitude': 51.4950485229492, 'longitude': 0.0835620015859604},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d72cf'),
  'geocode': {'latitude': 51.4903331, 'longitude': 0.0787421},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d72d0'),
  'geocode': {'latitude': 51.4903331, 'longitude': 0.0787421},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7324'),
  'geocode': {'latitude': 51.4978398, 'longitude': 0.0844204},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7346'),
  'geocode': {'latitude': 51.4918377, 'longitude': 0.0774802},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7360'),
  'geocode': {'latitude': 51.4942476, 'longitude': 0.0795886},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7388'),
  'geocode': {'latitude': 51.4914321899414, 'longitude': 0.075545996427536},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7395'),
  'geocode': {'latitude': 51.4935863, 'longitude': 0.0770593},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d73c4'),
  'geocode': {'latitude': 51.4923133850098, 'longitude': 0.0744580030441284},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d73d8'),
  'geocode': {'latitude': 51.4922421, 'longitude': 0.0739989},
  'scores': {'Hygiene': 0}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d6f40'),
  'geocode': {'latitude': 51.4870351, 'longitude': 0.0927429},
  'scores': {'Hygiene': 5}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7020'),
  'geocode': {'latitude': 51.4876089, 'longitude': 0.0909382},
  'scores': {'Hygiene': 5}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7033'),
  'geocode': {'latitude': 51.4878934, 'longitude': 0.0910104},
  'scores': {'Hygiene': 5}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d704e'),
  'geocode': {'latitude': 51.4877234, 'longitude': 0.0904552},
  'scores': {'Hygiene': 5}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7055'),
  'geocode': {'latitude': 51.4876718, 'longitude': 0.0903232},
  'scores': {'Hygiene': 5}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7083'),
  'geocode': {'latitude': 51.4817727, 'longitude': 0.083745},
  'scores': {'Hygiene': 5}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d70df'),
  'geocode': {'latitude': 51.4804420471191, 'longitude': 0.0812250003218651},
  'scores': {'Hygiene': 5}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d715a'),
  'geocode': {'latitude': 51.4870876, 'longitude': 0.0857591},
  'scores': {'Hygiene': 5}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d715b'),
  'geocode': {'latitude': 51.4810714, 'longitude': 0.0796803},
  'scores': {'Hygiene': 5}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7160'),
  'geocode': {'latitude': 51.4873374, 'longitude': 0.0858713},
  'scores': {'Hygiene': 5}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7170'),
  'geocode': {'latitude': 51.4808287, 'longitude': 0.078661},
  'scores': {'Hygiene': 5}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d717e'),
  'geocode': {'latitude': 51.4808120727539, 'longitude': 0.0785060003399849},
  'scores': {'Hygiene': 5}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d71ac'),
  'geocode': {'latitude': 51.4891019, 'longitude': 0.0857646},
  'scores': {'Hygiene': 5}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d71b4'),
  'geocode': {'latitude': 51.489315, 'longitude': 0.0859184},
  'scores': {'Hygiene': 5}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d71bb'),
  'geocode': {'latitude': 51.4893255, 'longitude': 0.0858325},
  'scores': {'Hygiene': 5}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d71d8'),
  'geocode': {'latitude': 51.4893112182617, 'longitude': 0.084697000682354},
  'scores': {'Hygiene': 5}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d71e9'),
  'geocode': {'latitude': 51.4861922, 'longitude': 0.0809311},
  'scores': {'Hygiene': 5}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d71f0'),
  'geocode': {'latitude': 51.4899426, 'longitude': 0.0846755},
  'scores': {'Hygiene': 5}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d72ce'),
  'geocode': {'latitude': 51.4903331, 'longitude': 0.0787421},
  'scores': {'Hygiene': 5}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7383'),
  'geocode': {'latitude': 51.4898490905762, 'longitude': 0.074074998497963},
  'scores': {'Hygiene': 5}},
 {'RatingValue': '5',
  '_id': ObjectId('63cc960826f9d622e55d7393'),
  'geocode': {'latitude': 51.4935863, 'longitude': 0.0770593},
  'scores': {'Hygiene': 5}}]

In [249]:
# Convert result to Pandas DataFrame
resuls_df = pd.DataFrame(results)

resuls_df.head(5)

,_id,RatingValue,scores,geocode
0,63cc960826f9d622e55d6f68,5,{'Hygiene': 0},"{'longitude': 0.0924199968576431, 'latitude': ..."
1,63cc960826f9d622e55d6f76,5,{'Hygiene': 0},"{'longitude': 0.0925370007753372, 'latitude': ..."
2,63cc960826f9d622e55d6f93,5,{'Hygiene': 0},"{'longitude': 0.09208, 'latitude': 51.4873437}"
3,63cc960826f9d622e55d6fab,5,{'Hygiene': 0},"{'longitude': 0.0859939977526665, 'latitude': ..."
4,63cc960826f9d622e55d6faf,5,{'Hygiene': 0},"{'longitude': 0.0912164, 'latitude': 51.4867296}"

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [ ]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
# 2. Groups the matches by Local Authority
# 3. Sorts the matches from highest to lowest

match_query = {'$match': {'scores.Hygiene': {'$eg': 0}}}

group_query = {'$group': {'_id': '$'}}

# Print the number of documents in the result

# Print the first 10 results

In [ ]:
# Convert the result to a Pandas DataFrame

# Display the number of rows in the DataFrame

# Display the first 10 rows of the DataFrame